# Generated by Django 5.0.4 on 2024-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
    ]
